// auth
export const SET_USERNAME = 'SET_USERNAME'
export const LOGIN = 'LOGIN'
export const INVALIDATE_LOGIN = 'INVALIDATE_LOGIN'
export const LOGOUT = 'LOGOUT'
export const NOTIFY_LOGOUT = 'NOTIFY_LOGOUT'
export const LOAD_USER = 'LOAD_USER'

// universe
export const REQUEST_UNIVERSE = 'REQUEST_UNIVERSE'
export const LOAD_UNIVERSE = 'LOAD_UNIVERSE'

// socketio
export const CONNECT_SOCKET = 'CONNECT_SOCKET'
export const DISCONNECT_SOCKET = 'DISCONNECT_SOCKET'
export const AVAILABLE_SOCKET = 'AVAILABLE_SOCKET'
export const UNAVAILABLE_SOCKET = 'UNAVAILABLE_SOCKET'
export const HIDE_SOCKET_NOTIFICATION = 'HIDE_SOCKET_NOTIFICATION'

// players
export const REQUEST_PLAYERS = 'REQUEST_PLAYERS'
export const LOAD_PLAYERS = 'LOAD_PLAYERS'
export const ADD_PLAYER = 'ADD_PLAYER'
export const REMOVE_PLAYER = 'REMOVE_PLAYER'
