// game
export const SET_VELOCITY = 'SET_VELOCITY'
export const SET_ENERGY = 'SET_ENERGY'
export const SET_ANGLE = 'SET_ANGLE'
export const REFRESH_GAME = 'REFRESH_GAME'

// auth
export const SET_USERNAME = 'SET_USERNAME'
export const CONNECT_USER = 'CONNECT_USER'
export const DISCONNECT_USER = 'DISCONNECT_USER'

// universe
export const LOAD_UNIVERSE = 'LOAD_UNIVERSE'

// socket
export const CONNECT_SOCKET = 'CONNECT_SOCKET'
export const DISCONNECT_SOCKET = 'DISCONNECT_SOCKET'
export const HIDE_SOCKET_NOTIFICATION = 'HIDE_SOCKET_NOTIFICATION'
